org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21
minecraft_version_range=[1.21, 1.22)
neo_version=21.0.157
neo_version_range=[21,)
loader_version_range=[4,)
jade_version=5591256

mod_id=everyxdance
mod_name=EveryXDance
mod_license=MIT
mod_version=2.0.1
mod_authors=Liu Dongyu
mod_description=As we know, piglins can dance. So can other mobs dance? The answer is YES!