name: New Feature Request
description: What features would you like to add in EveryXDance?
title: "[Enhancement]: "
labels: [ "Enhancement" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your supporting!
  - type: checkboxes
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of the feature would you describe?
      options:
      - label: Dance Animation
      - label: Mod Porting
      - label: Mod Compatibility
      - label: Dependency Development (API or Documentation)
      - label: Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description of the feature
      description: What can EveryXDance mod do for you?
      placeholder: Feel free to describe what you thought :)
    validations:
      required: true